//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourDuLich.TourService1Ref {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KhachSan", Namespace="http://schemas.datacontract.org/2004/07/TourService1")]
    [System.SerializableAttribute()]
    public partial class KhachSan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string diadiemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double giaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string kichthuocField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int sogiuongField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string diadiem {
            get {
                return this.diadiemField;
            }
            set {
                if ((object.ReferenceEquals(this.diadiemField, value) != true)) {
                    this.diadiemField = value;
                    this.RaisePropertyChanged("diadiem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double gia {
            get {
                return this.giaField;
            }
            set {
                if ((this.giaField.Equals(value) != true)) {
                    this.giaField = value;
                    this.RaisePropertyChanged("gia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string kichthuoc {
            get {
                return this.kichthuocField;
            }
            set {
                if ((object.ReferenceEquals(this.kichthuocField, value) != true)) {
                    this.kichthuocField = value;
                    this.RaisePropertyChanged("kichthuoc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loai {
            get {
                return this.loaiField;
            }
            set {
                if ((object.ReferenceEquals(this.loaiField, value) != true)) {
                    this.loaiField = value;
                    this.RaisePropertyChanged("loai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int sogiuong {
            get {
                return this.sogiuongField;
            }
            set {
                if ((this.sogiuongField.Equals(value) != true)) {
                    this.sogiuongField = value;
                    this.RaisePropertyChanged("sogiuong");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XeKhach", Namespace="http://schemas.datacontract.org/2004/07/TourService1")]
    [System.SerializableAttribute()]
    public partial class XeKhach : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XeLua", Namespace="http://schemas.datacontract.org/2004/07/TourService1")]
    [System.SerializableAttribute()]
    public partial class XeLua : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MayBay", Namespace="http://schemas.datacontract.org/2004/07/TourService1")]
    [System.SerializableAttribute()]
    public partial class MayBay : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TourService1Ref.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/layDSKhachSan", ReplyAction="http://tempuri.org/IService1/layDSKhachSanResponse")]
        TourDuLich.TourService1Ref.KhachSan[] layDSKhachSan(string diadiem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/layDSKhachSan", ReplyAction="http://tempuri.org/IService1/layDSKhachSanResponse")]
        System.Threading.Tasks.Task<TourDuLich.TourService1Ref.KhachSan[]> layDSKhachSanAsync(string diadiem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/layDSXeKhach", ReplyAction="http://tempuri.org/IService1/layDSXeKhachResponse")]
        TourDuLich.TourService1Ref.XeKhach[] layDSXeKhach(string diemxuatphat, string diemden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/layDSXeKhach", ReplyAction="http://tempuri.org/IService1/layDSXeKhachResponse")]
        System.Threading.Tasks.Task<TourDuLich.TourService1Ref.XeKhach[]> layDSXeKhachAsync(string diemxuatphat, string diemden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/layDSXeLua", ReplyAction="http://tempuri.org/IService1/layDSXeLuaResponse")]
        TourDuLich.TourService1Ref.XeLua[] layDSXeLua(string diemxuatphat, string diemden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/layDSXeLua", ReplyAction="http://tempuri.org/IService1/layDSXeLuaResponse")]
        System.Threading.Tasks.Task<TourDuLich.TourService1Ref.XeLua[]> layDSXeLuaAsync(string diemxuatphat, string diemden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/layDSMayBay", ReplyAction="http://tempuri.org/IService1/layDSMayBayResponse")]
        TourDuLich.TourService1Ref.MayBay[] layDSMayBay(string diemxuatphat, string diemden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/layDSMayBay", ReplyAction="http://tempuri.org/IService1/layDSMayBayResponse")]
        System.Threading.Tasks.Task<TourDuLich.TourService1Ref.MayBay[]> layDSMayBayAsync(string diemxuatphat, string diemden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/tong", ReplyAction="http://tempuri.org/IService1/tongResponse")]
        int tong(string x, string y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/tong", ReplyAction="http://tempuri.org/IService1/tongResponse")]
        System.Threading.Tasks.Task<int> tongAsync(string x, string y);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TourDuLich.TourService1Ref.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TourDuLich.TourService1Ref.IService1>, TourDuLich.TourService1Ref.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TourDuLich.TourService1Ref.KhachSan[] layDSKhachSan(string diadiem) {
            return base.Channel.layDSKhachSan(diadiem);
        }
        
        public System.Threading.Tasks.Task<TourDuLich.TourService1Ref.KhachSan[]> layDSKhachSanAsync(string diadiem) {
            return base.Channel.layDSKhachSanAsync(diadiem);
        }
        
        public TourDuLich.TourService1Ref.XeKhach[] layDSXeKhach(string diemxuatphat, string diemden) {
            return base.Channel.layDSXeKhach(diemxuatphat, diemden);
        }
        
        public System.Threading.Tasks.Task<TourDuLich.TourService1Ref.XeKhach[]> layDSXeKhachAsync(string diemxuatphat, string diemden) {
            return base.Channel.layDSXeKhachAsync(diemxuatphat, diemden);
        }
        
        public TourDuLich.TourService1Ref.XeLua[] layDSXeLua(string diemxuatphat, string diemden) {
            return base.Channel.layDSXeLua(diemxuatphat, diemden);
        }
        
        public System.Threading.Tasks.Task<TourDuLich.TourService1Ref.XeLua[]> layDSXeLuaAsync(string diemxuatphat, string diemden) {
            return base.Channel.layDSXeLuaAsync(diemxuatphat, diemden);
        }
        
        public TourDuLich.TourService1Ref.MayBay[] layDSMayBay(string diemxuatphat, string diemden) {
            return base.Channel.layDSMayBay(diemxuatphat, diemden);
        }
        
        public System.Threading.Tasks.Task<TourDuLich.TourService1Ref.MayBay[]> layDSMayBayAsync(string diemxuatphat, string diemden) {
            return base.Channel.layDSMayBayAsync(diemxuatphat, diemden);
        }
        
        public int tong(string x, string y) {
            return base.Channel.tong(x, y);
        }
        
        public System.Threading.Tasks.Task<int> tongAsync(string x, string y) {
            return base.Channel.tongAsync(x, y);
        }
    }
}
